# Generated by Django 4.2.4 on 2023-10-21 18:00

from django.db import migrations


def age_group(apps, schema_editor):
    Person = apps.get_model("main_app", "Person")
    all_persons = Person.objects.all()

    for person in all_persons:
        if person.age <= 12:
            person.age_group = 'Child'
        elif 12 <= person.age <= 17:
            person.age_group = 'Teen'
        else:
            person.age_group = 'Adult'
        person.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [migrations.RunPython(age_group),
    ]
