# Generated by Django 4.2.4 on 2023-10-21 18:35

from django.db import migrations

def set_price(apps,schema_editor):
    Smartphone = apps.get_model("main_app","Smartphone")
    all_smartphones = Smartphone.objects.all()

    for smartphone in all_smartphones:
        smartphone.price = len(smartphone.brand) * 120
        smartphone.save()

def set_category(apps, schema_editor):
    Smartphone = apps.get_model("main_app", "Smartphone")
    all_smartphones = Smartphone.objects.all()

    for smartphone in all_smartphones:
        if smartphone.price >= 750:
            smartphone.category = 'Expensive'
        else:
            smartphone.category = 'Cheap'

        smartphone.save()



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [migrations.RunPython(set_price),
                  migrations.RunPython(set_category)
    ]
