# Generated by Django 4.2.4 on 2023-10-21 18:51

from django.db import migrations
from datetime import timedelta

def set_delivery_and_warranty(apps,schema_editor):
    Order = apps.get_model("main_app", "Order")
    all_orders = Order.objects.all()

    for order in all_orders:
        if order.status == 'Pending':
            order.delivery = order.order_date + timedelta(days=3)
        elif order.status == 'Completed':
            order.warranty = '24 months'
        else:
            order.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [migrations.RunPython(set_delivery_and_warranty)
    ]
